# Starter pipeline


trigger:
- master

pool: 'Default'

steps:
- checkout: self
  clean: true
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -Name SqlServer -Force' 
  
- task: PowerShell@2
  inputs:
    filePath: $(System.DefaultWorkingDirectory)/Scripts/Powershell/RunInHomolog.ps1